spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todotask
    username: root
    password: Aa123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
